version: "3"
services:
  terminal:
    build: terminal
    volumes:
      - "apk-volume:/data"
  static-server:
    build: static-server
    volumes:
      - "apk-volume:/public"
    ports:
      - "8081:8080"
  server:
    build: server
    ports:
      - "8080:8080"

volumes:
    apk-volume: 