name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy to google server
      run: wget http://35.235.48.125:9000/hooks/deploy-cashmanager
